# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
env:
  - DJANGO=1.8.2
  - DJANGO=1.7.8
  - DJANGO=1.4.20

# Exclude python 3.3/django 1.4 - not a supported combination
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO==1.4.20

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-test.txt
  - pip install Django==$DJANGO

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source permatrix runtests.py

# report coverage to coveralls.io
after_success: coveralls
